=== nzzdev/Q-imageslider/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Bildslider",
  "properties": {
    "title": {
      "title": "Titel",
      "type": "string"
    },
    "subtitle": {
      "title": "Untertitel",
      "type": "string"
    },
    "images": {
      "title": "Bilder",
      "type": "array",
      "items": {
        "title": "Bild",
        "type": "object",
        "minItems": 2,
        "properties": {
          "file": {
            "type": "object",
            "Q:type": "files",
            "Q:options": {
              "maxFiles": 1,
              "acceptedFiles": "image/*",
              "fileProperties": {
                "url": "url",
                "key": "key",
                "size": "size",
                "width": "width",
                "height": "height"
              }
            }
          },
          "label": {
            "title": "Label",
            "type": "string"
          },
          "caption": {
            "title": "Legende",
            "type": "string"
          },
          "credit": {
            "title": "Credit",
            "type": "string"
          }
        },
        "required": [
          "label",
          "caption",
          "credit"
        ]
      }
    },
    "sources": {
      "title": "Quellen",
      "type": "array",
      "items": {
        "type": "object",
        "title": "Quelle",
        "properties": {
          "text": {
            "title": "Text",
            "type": "string"
          },
          "link": {
            "Q:type": "link",
            "title": "Link",
            "type": "object",
            "properties": {
              "url": {
                "title": "Url",
                "type": "string"
              },
              "isValid": {
                "type": "boolean"
              }
            }
          }
        },
        "required": ["text"]
      }
    },
    "notes": {
      "title": "Anmerkungen",
      "type": "string"
    }
  },
  "required": [
    "title",
    "images"
  ]
}

=== nzzdev/Q-imageslider/resources/fixtures/data/five-images.json
{
  "title": "Wandel im Verborgenen",
  "subtitle": "Die NZZ hat Ansichtskarten von anno dazumal denselben Perspektiven von heute gegenübergestellt. Manifest wurden landschaftlicher, klimatischer und wirtschaftlicher Wandel und Merkmale der Politik.",
  "images": [
    {
      "url": "https://img.nzz.ch/s=w540,pd1/o=75/http://nzz-img.s3.amazonaws.com/2017/8/10/98ee4bb0-f8a1-40be-94f4-5a448fe63082.jpeg",
      "label": "1965",
      "caption": "Ansichtskarte, versendet 1965: Der Verkehr auf dem Zürcher Bahnhofplatz wird von Hand geregelt.",
      "credit": "(Bild: Simon Tanner / NZZ)"
    },
    {
      "url": "https://img.nzz.ch/s=w540,pd1/o=75/http://nzz-img.s3.amazonaws.com/2017/8/10/e9930834-1b84-4186-80c4-23ba7512519a.jpeg",
      "label": "1985",
      "caption": "Das heutige Bild ist ähnlich. Grundlegend verändert hat sich der HB aber unter der Erde.",
      "credit": "(Bild: Simon Tanner / NZZ)"
    },
    {
      "url": "https://img.nzz.ch/s=w540,pd1/o=75/http://nzz-img.s3.amazonaws.com/2017/8/10/98ee4bb0-f8a1-40be-94f4-5a448fe63082.jpeg",
      "label": "1995",
      "caption": "Ansichtskarte, versendet 1965: Der Verkehr auf dem Zürcher Bahnhofplatz wird von Hand geregelt.",
      "credit": "(Bild: Simon Tanner / NZZ)"
    },
    {
      "url": "https://img.nzz.ch/s=w540,pd1/o=75/http://nzz-img.s3.amazonaws.com/2017/8/10/e9930834-1b84-4186-80c4-23ba7512519a.jpeg",
      "label": "2005",
      "caption": "Das heutige Bild ist ähnlich. Grundlegend verändert hat sich der HB aber unter der Erde.",
      "credit": "(Bild: Simon Tanner / NZZ)"
    },
    {
      "url": "https://img.nzz.ch/s=w540,pd1/o=75/http://nzz-img.s3.amazonaws.com/2017/8/10/98ee4bb0-f8a1-40be-94f4-5a448fe63082.jpeg",
      "label": "2017",
      "caption": "Ansichtskarte, versendet 1965: Der Verkehr auf dem Zürcher Bahnhofplatz wird von Hand geregelt.",
      "credit": "(Bild: Simon Tanner / NZZ)"
    }
  ],
  "sources": [
    {
      "text": "Zürcher Verkehrsverbund",
      "link": {
        "url": "https://www.zvv.ch/",
        "isValid": true
      }
    }
  ],
  "notes": "Anmerkung"
}

=== nzzdev/Q-imageslider/resources/fixtures/data/two-images-long-labels.json
{
  "title": "FIXTURE: two images - long labels",
  "subtitle": "Die NZZ hat Ansichtskarten von anno dazumal denselben Perspektiven von heute gegenübergestellt. Manifest wurden landschaftlicher, klimatischer und wirtschaftlicher Wandel und Merkmale der Politik.",
  "images": [
    {
      "file": {
        "url": "https://img.nzz.ch/s=w540,pd1/o=75/http://nzz-img.s3.amazonaws.com/2017/8/10/98ee4bb0-f8a1-40be-94f4-5a448fe63082.jpeg",
        "key": "",
        "size": "37.9",
        "width": "540",
        "height": "338"
      },
      "label": "1965 - Es sind auch sehr sehr lange Labels möglich",
      "caption": "Ansichtskarte, versendet 1965: Der Verkehr auf dem Zürcher Bahnhofplatz wird von Hand geregelt.",
      "credit": "(Bild: Simon Tanner / NZZ)"
    },
    {
      "file": {
        "url": "https://img.nzz.ch/s=w540,pd1/o=75/http://nzz-img.s3.amazonaws.com/2017/8/10/e9930834-1b84-4186-80c4-23ba7512519a.jpeg",
        "key": "",
        "size": "37.9",
        "width": "540",
        "height": "338"
      },
      "url": "https://img.nzz.ch/s=w540,pd1/o=75/http://nzz-img.s3.amazonaws.com/2017/8/10/e9930834-1b84-4186-80c4-23ba7512519a.jpeg",
      "label": "2017",
      "caption": "Das heutige Bild ist ähnlich. Grundlegend verändert hat sich der HB aber unter der Erde.",
      "credit": "(Bild: Simon Tanner / NZZ)"
    }
  ],
  "sources": [
    {
      "text": "Zürcher Verkehrsverbund",
      "link": {
        "url": "https://www.zvv.ch/",
        "isValid": true
      }
    }
  ],
  "notes": "Anmerkung"
}
